server:
  port: 9002

spring:
  mail:
    host: smtp.qq.com
    username: 2363807763@qq.com
    password: rvadbyjyqfbtdifb
  resources:
    static-locations: classpath:/resources/, classpath:/static/ ,classpath:/templates/

mail:
  fromMail:
    addr: 2363807763@qq.com # 发邮件者

#日志级别
logging:
  level:
    root: warn
    com.scaffold.test.mapper: trace
    com.scaffold.test.task: trace